#!/usr/bin/env bash

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

echo "$changed_files" | grep --quiet "requirements.txt" && eval "sudo pip install -U -r requirements.txt"
cd julius_conf
echo "$changed_files" | grep --quiet "julius_conf/jeeves.grammar" && eval "mkdfa.pl jeeves"
echo "$changed_files" | grep --quiet "julius_conf/jeeves.voca" && eval "mkdfa.pl jeeves"
